version: '3'

services:
  cmake:
    container_name: real-time-mapping-cpp
    build:
      context: .
      dockerfile: Dockerfile

    tty: true
    command: /bin/bash

    volumes:
      - ./:/home
